import { doc, setDoc, getDoc, updateDoc, arrayUnion, arrayRemove, Timestamp } from 'firebase/firestore';
import { db } from '../config/firebase';
import { UserProfile } from '../types';
const UC = 'users';
export const createUserProfile = async (uid: string, data: { displayName: string; email: string; photoURL?: string }): Promise<void> => { await setDoc(doc(db,UC,uid),{...data,favorites:[],createdAt:Timestamp.now()}); };
export const getUserProfile = async (uid: string): Promise<UserProfile|null> => { const ds = await getDoc(doc(db,UC,uid)); if(!ds.exists())return null; return {uid,...ds.data()} as UserProfile; };
export const updateUserProfile = async (uid: string, data: Partial<UserProfile>): Promise<void> => { await updateDoc(doc(db,UC,uid),{...data}); };
export const addToFavorites = async (uid: string, placeId: string): Promise<void> => { await updateDoc(doc(db,UC,uid),{favorites:arrayUnion(placeId)}); };
export const removeFromFavorites = async (uid: string, placeId: string): Promise<void> => { await updateDoc(doc(db,UC,uid),{favorites:arrayRemove(placeId)}); };
export const getFavoritePlaces = async (favoriteIds: string[]): Promise<any[]> => { if(favoriteIds.length===0)return[]; const { getPlaceById } = await import('./places'); const results = await Promise.all(favoriteIds.map(id=>getPlaceById(id))); return results.filter(p=>p!==null); };
